Add match-field-type property in releated
rwynn/monstache pull request #470
Opened 2020-12-18 04:00 UTC by minhuyen

I added match-field-type property support 2 options: string vs ObjectId in related config. The default value is ObjectId.
It supports convert src-field to string if the match-field-type value is a string. 
The pull request support for #464 issue

2020-12-20 17:21 UTC, rwynn commented
Hi @minhuyen thanks for your contribution to monstache.  Can we work on this PR together a little before merging the feature?  

My suggestions would be:

1. Assume no default type for the `srcData` and thus if the user does not specify `match-field-type` then keep it as empty string instead of defaulting to `ObjectID`
2. Extract the actual data conversion into a separate function.  In this function support converting srcData from `string` to `objectId` (via primitive.ObjectIDFromHex) or `objectId` to `string` like you already added depending on the value of `match-field-type`.  Use the exact `alias` values from https://docs.mongodb.com/manual/reference/bson-types/ as the accepted inputs for `match-field-type`.  Have the function return an error in the case where the conversion fails.  
3. Add a few tests to monstache_test.go to cover conversion from `string` to `objectId` or vice versa and also some error cases. 

Thanks,
Ryan

2020-12-21 07:37 UTC, minhuyen commented
Hi @rwynn 
I have updated the code according to your suggestion.
Please check! Thanks

2020-12-21 17:00 UTC, rwynn commented
Hi @minhuyen thanks, I like the changes you have made so far.  

Can you please update your branch so that the changes listed on this PR (see Files changed tab) are only those related to this feature?  I think you may need to merge your branch with the latest from the `rel6` branch.  

That will make it easier to discuss.  Thanks!

2020-12-22 02:05 UTC, minhuyen commented
Hi @rwynn 
I updated my branch. Can you check again?
Thanks.

2020-12-24 05:08 UTC, rwynn requested changes

2020-12-24 05:08 UTC, rwynn commented on monstache.go
> +	MatchFieldType string `toml:"match-field-type"`
Can you run `gofmt` on this file?

2020-12-24 05:08 UTC, rwynn commented on monstache.go
> +	defer func() {
I don't think the defer and recover is necessary here.

2020-12-24 05:08 UTC, rwynn commented on monstache.go
> +				if r.MatchFieldType == "objectId" {
Can you extract this part into one more function, e.g. `convertSrcDataToMatchFieldType` like

```golang
if r.MatchFieldType != "" {
if srcData, err = convertSrcDataToMatchFieldType(srcData, r.MatchFieldtype); err != nil {
						ic.processErr(err)
						continue
					}
}
```
This new function `convertSrcDataToMatchFieldType` can then check which of `convertSrcDataToObjectId` or `convertSrcDataToString` to invoke.

2020-12-24 09:29 UTC, minhuyen commented
Hi, @rwynn thanks for your feedback!

I updated the code. Can you review it?

Thanks

2020-12-24 15:54 UTC, rwynn requested changes
This is looking really good.  Thanks for your patience and working with me on it.

Just had one last request that I forgot to add to the last review.  Then I think I'm good to merge it.

2020-12-24 15:54 UTC, rwynn commented on monstache.go
> +		value = srcData.(primitive.ObjectID).Hex()
Can you change this line to `v.Hex()` since v will already be ObjectID here?

2020-12-25 02:51 UTC, minhuyen commented
I have updated it.
Thanks for your support

2020-12-25 06:00 UTC, rwynn approved these changes
Thanks for contributing this feature!

2020-12-25 06:01 UTC, merged